# @package _group_
_target_: dpr_scale.task.mtsplade_task.MultiTermRetrieverTask
shared_model: false
in_batch_eval: false
# Temporary till we reformat LightningModule
datamodule: null
warmup_steps: null
pretrained_checkpoint_path:
